apiVersion: apps/v1
kind: Deployment
metadata:
  name: github-runner
  namespace: github-actions
spec:
  replicas: 1
  selector:
    matchLabels:
      app: github-runner
  template:
    metadata:
      labels:
        app: github-runner
    spec:
      serviceAccountName: github-runner
      containers:
      - name: runner
        image: myoung34/github-runner:latest
        env:
        - name: RUNNER_SCOPE
          value: "org" # Required: Register as an organization runner
        - name: ORG_NAME
          value: "kxn-organization" # Required: Replace with your GitHub organization name
        - name: ACCESS_TOKEN
          value: "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" # Required: Replace with a valid GitHub PAT with necessary scopes
        - name: LABELS
          value: "self-hosted" # Required: At least one label is mandatory
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1"
