name: Infra Create Pipeline
on:
  push:
    branches:
      - main
env:
  GOOGLE_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
  
jobs:
  run-shell-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run shell script
      run: |
        ls -ltr
        chmod +x ./trigger.sh
        ./trigger.sh 
